version: '3'

services:

  mysql:
    container_name: minecraft_mysql
    image: mariadb:10.5
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: "Asia/Tokyo"
    env_file:
      - ./mysql/.env
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --performance-schema=false --expire_logs_days=1
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - internal_network

  web:
    container_name: minecraft_web
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./waterfall/config.yml:/app/config.yml
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Tokyo
      - PORT=3000
      - HOSTNAME=minecraft.iamtakagi.net
    networks:
      - proxy_network
      - internal_network
    restart: always

  # Waterfall Proxy
  waterfall:
    container_name: waterfall
    image: ghcr.io/kanagawa-iamtakagi-net/waterfall:2022.04.26
    volumes:
      - ./waterfall:/app
      - /etc/localtime:/etc/localtime:ro
    tty: true
    stdin_open: true
    environment:
      TZ: "Asia/Tokyo"
      JAVA_OPTS: "-Xms256M -Xmx512M"
    networks:
      - proxy_network
      - internal_network
    restart: always
    depends_on:
      - mysql

  # Paper Servers
  hub:
    container_name: hub
    image: ghcr.io/kanagawa-iamtakagi-net/paper:2022.04.26
    volumes:
      - ./hub:/app
      - /etc/localtime:/etc/localtime:ro
    tty: true
    stdin_open: true
    environment:
      TZ: "Asia/Tokyo"
      JAVA_OPTS: "-Xms1G -Xmx2G"
    networks:
      - default
      - internal_network
    restart: always
    depends_on:
      - mysql

  lab: 
    container_name: lab
    image: ghcr.io/kanagawa-iamtakagi-net/paper:2022.04.26
    volumes:
      - ./lab:/app
      - /etc/localtime:/etc/localtime:ro
    tty: true
    stdin_open: true
    environment:
      TZ: "Asia/Tokyo"
      JAVA_OPTS: "-Xms1G -Xmx2G"
    networks:
      - default
      - internal_network
    restart: always
    depends_on:
      - mysql
    
  survival: 
    container_name: survival
    image: ghcr.io/kanagawa-iamtakagi-net/paper:2022.04.26
    volumes:
      - ./survival:/app
      - /etc/localtime:/etc/localtime:ro
    tty: true
    stdin_open: true
    environment:
      TZ: "Asia/Tokyo"
      JAVA_OPTS: "-Xms1G -Xmx2G"
    networks:
      - default
      - internal_network
    restart: always
    depends_on:
      - mysql

networks:
  proxy_network:
    external: true
  internal_network:
    internal: true